### ISSUE TITLE
Problem initializing 

### ISSUE THREAD

**Issue by logopk** [aaronweaver/docker-DefectDojo#4]
Following the installation instructions, no changes to the basic setup after a fresh clone, I get a restart cycle on the dojo container.

docker 17.06 on macOS with VMware

dojo_1   |  * Starting MySQL database server mysqld
dojo_1   |    ...done.
**dojo_1   | No passwd entry for user 'dojo'**

Please advise. How can I get to the root cause? 

Peter

**Comment by Mason-Fan** [comment]
also got the issue on my side, is there any workaround?

**Comment by aaronweaver** [comment]
Fixed in latest docker image.
